language: python
python:
  - 3.5
install:
  - pip install sphinx sphinx_rtd_theme recommonmark
script: make html

deploy:
  provider: pages
  local-dir: build/html/
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master